- name: ollama/ministral-3:8b
  extra_params:
    num_ctx: 32768
- name: ollama_chat/ministral-3:8b
  extra_params:
    num_ctx: 32768
- name: ollama/llama3.2:latest
  extra_params:
    num_ctx: 131072
- name: ollama_chat/llama3.2:latest
  extra_params:
    num_ctx: 131072
- name: ollama/deepseek-r1:8b
  extra_params:
    num_ctx: 8192
- name: ollama_chat/deepseek-r1:8b
  extra_params:
    num_ctx: 8192
- name: ollama/qwen3:8b
  extra_params:
    num_ctx: 40960
- name: ollama_chat/qwen3:8b
  extra_params:
    num_ctx: 40960
- name: ollama/gemma3:4b
  extra_params:
    num_ctx: 131072
- name: ollama_chat/gemma3:4b
  extra_params:
    num_ctx: 131072
